spring:
  jpa:
    open-in-view: false

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      base-path: /api/v1/fitness/management
      exposure:
        include: "prometheus,health,info"
app:
  cors:
    allowed-origins:
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - PATCH

security:
  jwt:
    duration: 86400
    signing-key: fitness-rest-application-local-secret-key

    
#resilience4j:
#  circuitbreaker:
##      workloadService:
#        failureRateThreshold: 50
#        slowCallRateThreshold: 60
#        slowCallDurationThreshold: 2s
#        permittedNumberOfCallsInHalfOpenState: 2
##        maxWaitDurationInHalfOpenState: 5s
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        waitDurationInOpenState: 10s
#        automaticTransitionFromOpenToHalfOpenEnabled: true


#service:
#  trainer-workload:
#    url: http://localhost:8080/api/v1/workloads/


