server:
    port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: asror
    password: asror
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 

security:
  jwt:
     duration: 86400
     signing-key: fitness-rest-application-dev-secret-key