server:
    port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/postgres
    username: asror
    password: asror
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop # Change to 'none' or 'validate' in production
    show-sql: true  # Enable SQL logging (optional)
security:
  jwt:
     duration: 86400
     signing-key: fitness-rest-application-dev-secret-key