server:
  port: 8083

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: fitness-service
          uri: lb:http://FITNESS-SERVICE
          predicates:
            - Path=/api/v1/fitness/**

        - id: workload-service
          uri: lb:http://WORKLOAD-SERVICE
          predicates:
            - Path=/api/v1/workloads/**

        - id: auth-service
          uri: lb:http://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**
eureka:
  instance:
    hostname: gateway-server
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}