server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  
eureka:
  instance:
    hostname: workload-service
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}