package com.example.auth_service.jms.outbox;

public enum EventType {
    WORKLOAD_UPDATE_REQUESTED,
    TRAINEE_REGISTER_REQUESTED,
    TRAINER_REGISTER_REQUESTED,

    TRAINEE_REGISTER_RESPONDED,
    TRAINER_REGISTER_RESPONDED,
    WORKLOAD_UPDATE_RESPONDED
}
