package com.example.fitness_service.jms.outbox;

public enum EventType {
    WORKLOAD_UPDATE_REQUESTED,
    TRAINEE_CREATE_REQUESTED,
    TRAINER_CREATE_REQUESTED,

    TRAINEE_CREATE_SUCCESS,
    TRAINEE_CREATE_FAILED,

    TRAINER_CREATED_SUCCESS,
    TRAINER_CREATE_FAILED,
}
